import type { Config } from 'tailwindcss';

const config: Config = {
  darkMode: ['class'],
  content: [
    './pages/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
    './app/**/*.{js,ts,jsx,tsx,mdx}',
    './config/**/*.{js,ts,jsx,tsx,mdx}',
    './content/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    container: {
      center: true,
      padding: { DEFAULT: '1rem', sm: '1.5rem', lg: '2rem' },
      screens: { '2xl': '1280px' },
    },
    extend: {
      colors: {
        background: 'hsl(var(--background))',
        foreground: 'hsl(var(--foreground))',
        card: { DEFAULT: 'hsl(var(--card))', foreground: 'hsl(var(--card-foreground))' },
        popover: { DEFAULT: 'hsl(var(--popover))', foreground: 'hsl(var(--popover-foreground))' },
        primary: { DEFAULT: 'hsl(var(--primary))', foreground: 'hsl(var(--primary-foreground))' },
        secondary: { DEFAULT: 'hsl(var(--secondary))', foreground: 'hsl(var(--secondary-foreground))' },
        muted: { DEFAULT: 'hsl(var(--muted))', foreground: 'hsl(var(--muted-foreground))' },
        accent: { DEFAULT: 'hsl(var(--accent))', foreground: 'hsl(var(--accent-foreground))' },
        destructive: { DEFAULT: 'hsl(var(--destructive))', foreground: 'hsl(var(--destructive-foreground))' },
        border: 'hsl(var(--border))',
        input: 'hsl(var(--input))',
        ring: 'hsl(var(--ring))',
        chart: {
          '1': 'hsl(var(--chart-1))', '2': 'hsl(var(--chart-2))',
          '3': 'hsl(var(--chart-3))', '4': 'hsl(var(--chart-4))', '5': 'hsl(var(--chart-5))',
        },
        cube: {
          navy: 'hsl(var(--cube-navy))',
          green: 'hsl(var(--cube-green))',
          'green-bright': 'hsl(var(--cube-green-bright))',
          'green-dark': 'hsl(var(--cube-green-dark))',
          blue: 'hsl(var(--cube-blue))',
          soft: 'hsl(var(--cube-soft))',
          amber: 'hsl(var(--cube-amber))',
          red: 'hsl(var(--cube-red))',
          success: 'hsl(var(--cube-success))',
        },
        brand: {
          navy: 'hsl(var(--cube-navy))',
          blue: 'hsl(var(--cube-blue))',
          green: 'hsl(var(--cube-green))',
          'green-bright': 'hsl(var(--cube-green-bright))',
          'green-dark': 'hsl(var(--cube-green-dark))',
          surface: 'hsl(var(--surface))',
          'surface-muted': 'hsl(var(--surface-muted))',
          'text-primary': 'hsl(var(--text-primary))',
          'text-secondary': 'hsl(var(--text-secondary))',
          'text-inverse': 'hsl(var(--text-inverse))',
          'border-strong': 'hsl(var(--border-strong))',
          success: 'hsl(var(--success))',
          warning: 'hsl(var(--warning))',
          critical: 'hsl(var(--critical))',
          information: 'hsl(var(--information))',
        },
      },
      fontFamily: {
        sans: ['var(--font-inter)', 'system-ui', 'sans-serif'],
        heading: ['var(--font-inter)', 'system-ui', 'sans-serif'],
      },
      borderRadius: {
        sm: 'var(--radius-sm)',
        DEFAULT: 'var(--radius-md)',
        md: 'var(--radius-md)',
        lg: 'var(--radius-lg)',
        xl: 'var(--radius-xl)',
        '2xl': 'var(--radius-xl)',
      },
      boxShadow: {
        subtle: 'var(--shadow-subtle)',
        card: 'var(--shadow-card)',
        hover: 'var(--shadow-hover)',
        overlay: 'var(--shadow-overlay)',
      },
      spacing: {
        section: '6rem',
        'section-lg': '8rem',
        'section-sm': '4rem',
      },
      maxWidth: {
        narrow: '760px',
        standard: '1280px',
        wide: '1440px',
      },
      keyframes: {
        'accordion-down': { from: { height: '0' }, to: { height: 'var(--radix-accordion-content-height)' } },
        'accordion-up': { from: { height: 'var(--radix-accordion-content-height)' }, to: { height: '0' } },
        'fade-in': { from: { opacity: '0', transform: 'translateY(8px)' }, to: { opacity: '1', transform: 'translateY(0)' } },
        'fade-in-up': { from: { opacity: '0', transform: 'translateY(16px)' }, to: { opacity: '1', transform: 'translateY(0)' } },
      },
      animation: {
        'accordion-down': 'accordion-down 0.2s ease-out',
        'accordion-up': 'accordion-up 0.2s ease-out',
        'fade-in': 'fade-in 0.4s ease-out',
        'fade-in-up': 'fade-in-up 0.5s ease-out',
      },
    },
  },
  plugins: [require('tailwindcss-animate')],
};
export default config;
