import type { Download } from '@/types/content';

export const downloads: Download[] = [
  {
    slug: 'basic-workplace-safety-checklist',
    title: 'Basic Workplace Safety Checklist',
    description: 'A general checklist covering common workplace safety areas for daily and periodic review.',
    fileType: 'PDF',
    version: '1.0',
    lastUpdated: '2024',
    category: 'Safety',
    requireEmail: false,
    published: true,
  },
  {
    slug: 'emergency-readiness-checklist',
    title: 'Emergency Readiness Checklist',
    description: 'A checklist to help organizations assess emergency preparedness, response plans, and equipment readiness.',
    fileType: 'PDF',
    version: '1.0',
    lastUpdated: '2024',
    category: 'Emergency',
    requireEmail: false,
    published: true,
  },
  {
    slug: 'fire-extinguisher-inspection-checklist',
    title: 'Fire Extinguisher Inspection Checklist',
    description: 'A checklist for periodic inspection of fire extinguishers, including condition, access, and service records.',
    fileType: 'PDF',
    version: '1.0',
    lastUpdated: '2024',
    category: 'Fire Safety',
    requireEmail: false,
    published: true,
  },
  {
    slug: 'daily-housekeeping-checklist',
    title: 'Daily Housekeeping Checklist',
    description: 'A checklist to support daily workplace cleanliness, organization, and hazard prevention through good housekeeping.',
    fileType: 'PDF',
    version: '1.0',
    lastUpdated: '2024',
    category: 'Housekeeping',
    requireEmail: false,
    published: true,
  },
  {
    slug: 'toolbox-talk-attendance-sheet',
    title: 'Toolbox Talk Attendance Sheet',
    description: 'A sign-on sheet for recording attendance at toolbox talks and short safety briefings.',
    fileType: 'PDF',
    version: '1.0',
    lastUpdated: '2024',
    category: 'Training',
    requireEmail: false,
    published: true,
  },
  {
    slug: 'incident-report-form',
    title: 'Incident Report Form',
    description: 'A structured form for reporting workplace incidents, including details, causes, and immediate actions.',
    fileType: 'PDF',
    version: '1.0',
    lastUpdated: '2024',
    category: 'Incident Management',
    requireEmail: false,
    published: true,
  },
  {
    slug: 'near-miss-report-form',
    title: 'Near-Miss Report Form',
    description: 'A form for reporting near-miss events to help organizations identify risks before incidents occur.',
    fileType: 'PDF',
    version: '1.0',
    lastUpdated: '2024',
    category: 'Incident Management',
    requireEmail: false,
    published: true,
  },
  {
    slug: 'corrective-action-register',
    title: 'Corrective Action Register',
    description: 'A register for tracking corrective actions, responsible persons, target dates, and completion status.',
    fileType: 'XLSX',
    version: '1.0',
    lastUpdated: '2024',
    category: 'Management',
    requireEmail: false,
    published: true,
  },
  {
    slug: 'ppe-issue-register',
    title: 'PPE Issue Register',
    description: 'A register for recording the issue of personal protective equipment to employees, including signatures and dates.',
    fileType: 'XLSX',
    version: '1.0',
    lastUpdated: '2024',
    category: 'Safety',
    requireEmail: false,
    published: true,
  },
  {
    slug: 'training-record-template',
    title: 'Training Record Template',
    description: 'A template for recording employee training, including topic, date, trainer, and attendance.',
    fileType: 'XLSX',
    version: '1.0',
    lastUpdated: '2024',
    category: 'Training',
    requireEmail: false,
    published: true,
  },
  {
    slug: 'monthly-workplace-inspection-checklist',
    title: 'Monthly Workplace Inspection Checklist',
    description: 'A comprehensive checklist for conducting monthly workplace inspections across key safety and compliance areas.',
    fileType: 'PDF',
    version: '1.0',
    lastUpdated: '2024',
    category: 'Safety',
    requireEmail: false,
    published: true,
  },
  {
    slug: 'visitor-safety-checklist',
    title: 'Visitor Safety Checklist',
    description: 'A checklist for ensuring visitor safety, including induction, PPE, escort requirements, and emergency information.',
    fileType: 'PDF',
    version: '1.0',
    lastUpdated: '2024',
    category: 'Safety',
    requireEmail: false,
    published: true,
  },
  {
    slug: 'contractor-induction-checklist',
    title: 'Contractor Induction Checklist',
    description: 'A checklist for inducting contractors on site safety rules, hazards, permits, and responsibilities.',
    fileType: 'PDF',
    version: '1.0',
    lastUpdated: '2024',
    category: 'Contractor Management',
    requireEmail: false,
    published: true,
  },
  {
    slug: 'chemical-register-template',
    title: 'Chemical Register Template',
    description: 'A template for maintaining a register of chemicals, including names, quantities, storage locations, and safety data sheets.',
    fileType: 'XLSX',
    version: '1.0',
    lastUpdated: '2024',
    category: 'Chemical Management',
    requireEmail: false,
    published: true,
  },
  {
    slug: 'waste-inspection-checklist',
    title: 'Waste Inspection Checklist',
    description: 'A checklist for inspecting waste storage, segregation, labelling, and disposal practices.',
    fileType: 'PDF',
    version: '1.0',
    lastUpdated: '2024',
    category: 'Environment',
    requireEmail: false,
    published: true,
  },
];
