import type { Industry } from '@/types/content';

export const industries: Industry[] = [
  {
    slug: 'restaurants',
    name: 'Restaurants & Food Service',
    shortName: 'Restaurants',
    cardSummary:
      'Food safety, kitchen safety, hygiene, fire readiness, employee wellbeing, and service consistency.',
    seoTitle: 'Restaurants & Food Safety Solutions | SAFE CUBE',
    metaDescription:
      'SAFE CUBE helps restaurants and food service businesses improve food safety, kitchen safety, hygiene, fire readiness, and service consistency.',
    heroHeading: 'Workplace Safety for Restaurants & Food Service',
    introduction:
      'SAFE CUBE helps restaurants, kitchens, and food service businesses identify food safety risks, kitchen hazards, hygiene gaps, fire readiness issues, and employee wellbeing concerns. We understand that food service environments combine heat, sharp equipment, fast-paced work, and customer-facing responsibilities, and we adapt our assessments and recommendations accordingly.',
    commonRisks: [
      'Kitchen fire hazards and grease buildup',
      'Food hygiene and temperature control failures',
      'Slips, trips, and falls from spills and grease',
      'Sharp equipment, cuts, and burns',
      'Employee wellbeing, fatigue, and heat exposure',
      'Emergency preparedness and evacuation readiness',
    ],
    safeCubeSupport: [
      'Kitchen safety assessments',
      'Food hygiene and handling reviews',
      'Fire readiness evaluations',
      'Employee health and safety guidance',
      'Compliance documentation support',
      'Staff training and toolbox talks',
    ],
    ctaLabel: 'GET FREE CUBE SCORE',
    ctaHref: '/cube-score',
    featured: true,
    iconName: 'industries',
  },
  {
    slug: 'healthcare',
    name: 'Healthcare',
    shortName: 'Healthcare',
    cardSummary:
      'Patient safety, infection-control practices, waste handling, occupational health, emergency readiness, and compliance.',
    seoTitle: 'Healthcare Safety & Compliance Solutions | SAFE CUBE',
    metaDescription:
      'SAFE CUBE helps healthcare facilities improve patient safety, infection control, waste handling, occupational health, and compliance.',
    heroHeading: 'Workplace Safety for Healthcare Facilities',
    introduction:
      'SAFE CUBE helps clinics, hospitals, and healthcare facilities address patient safety, infection control, medical waste handling, occupational health, emergency readiness, and regulatory compliance. We understand that healthcare environments carry unique risks and that safety performance directly affects patient trust and staff wellbeing.',
    commonRisks: [
      'Infection control gaps and hygiene practices',
      'Medical waste handling and disposal',
      'Needle-stick and sharps injuries',
      'Patient handling and ergonomic strain',
      'Emergency response readiness',
      'Regulatory and inspection compliance',
    ],
    safeCubeSupport: [
      'Infection-control assessments',
      'Waste management reviews',
      'Occupational health evaluations',
      'Emergency preparedness support',
      'Compliance documentation',
      'Staff awareness training',
    ],
    ctaLabel: 'GET FREE CUBE SCORE',
    ctaHref: '/cube-score',
    featured: true,
    iconName: 'industries',
  },
  {
    slug: 'manufacturing',
    name: 'Manufacturing',
    shortName: 'Manufacturing',
    cardSummary:
      'Machinery safety, process risk, quality control, chemical management, environmental impact, and operational consistency.',
    seoTitle: 'Manufacturing Safety & Quality Solutions | SAFE CUBE',
    metaDescription:
      'SAFE CUBE helps manufacturing businesses improve machinery safety, process risk management, quality control, chemical management, and operational consistency.',
    heroHeading: 'Workplace Safety for Manufacturing',
    introduction:
      'SAFE CUBE helps manufacturing businesses address machinery safety, process risks, quality control, chemical management, environmental impact, and operational consistency. We understand that manufacturing environments involve complex processes, heavy equipment, and multiple regulatory obligations.',
    commonRisks: [
      'Machinery and equipment hazards',
      'Process and quality failures',
      'Chemical storage and handling',
      'Environmental emissions and waste',
      'Noise and dust exposure',
      'Contractor and visitor safety',
    ],
    safeCubeSupport: [
      'Machinery safety assessments',
      'Quality control process reviews',
      'Chemical management guidance',
      'Environmental impact evaluations',
      'Compliance and documentation support',
      'Operator and supervisor training',
    ],
    ctaLabel: 'GET FREE CUBE SCORE',
    ctaHref: '/cube-score',
    featured: true,
    iconName: 'industries',
  },
  {
    slug: 'construction',
    name: 'Construction',
    shortName: 'Construction',
    cardSummary:
      'Site safety, work at height, excavation, lifting, electrical risk, permits, contractor control, and emergency readiness.',
    seoTitle: 'Construction Site Safety Solutions | SAFE CUBE',
    metaDescription:
      'SAFE CUBE helps construction businesses improve site safety, work at height, excavation, lifting, electrical risk, permits, and emergency readiness.',
    heroHeading: 'Workplace Safety for Construction',
    introduction:
      'SAFE CUBE helps construction businesses address site safety, work at height, excavation, lifting, electrical risk, permit-to-work systems, contractor control, and emergency readiness. We understand that construction sites are dynamic, with changing conditions and multiple contractors working simultaneously.',
    commonRisks: [
      'Work at height and fall hazards',
      'Excavation and ground works',
      'Lifting and crane operations',
      'Electrical hazards and temporary wiring',
      'Permit-to-work gaps',
      'Contractor and site control',
    ],
    safeCubeSupport: [
      'Site safety assessments',
      'Permit-to-work system reviews',
      'Contractor control guidance',
      'Emergency preparedness evaluations',
      'Compliance documentation support',
      'Site supervisor and worker training',
    ],
    ctaLabel: 'GET FREE CUBE SCORE',
    ctaHref: '/cube-score',
    featured: true,
    iconName: 'industries',
  },
  {
    slug: 'warehouses',
    name: 'Warehouses',
    shortName: 'Warehouses',
    cardSummary:
      'Storage safety, material handling, traffic management, fire protection, racking, loading areas, and inventory protection.',
    seoTitle: 'Warehouse Safety Solutions | SAFE CUBE',
    metaDescription:
      'SAFE CUBE helps warehouses improve storage safety, material handling, traffic management, fire protection, racking, loading areas, and inventory protection.',
    heroHeading: 'Workplace Safety for Warehouses',
    introduction:
      'SAFE CUBE helps warehouses address storage safety, material handling, traffic management, fire protection, racking integrity, loading areas, and inventory protection. We understand that warehouse environments combine vehicle movement, manual handling, and storage systems in a single operational space.',
    commonRisks: [
      'Material handling and manual lifting',
      'Forklift and traffic management',
      'Racking and storage integrity',
      'Fire protection gaps',
      'Loading and unloading areas',
      'Slips, trips, and falls',
    ],
    safeCubeSupport: [
      'Storage and racking assessments',
      'Traffic management reviews',
      'Fire protection evaluations',
      'Material handling guidance',
      'Compliance documentation support',
      'Warehouse staff training',
    ],
    ctaLabel: 'GET FREE CUBE SCORE',
    ctaHref: '/cube-score',
    featured: true,
    iconName: 'industries',
  },
  {
    slug: 'engineering-workshops',
    name: 'Engineering Workshops',
    shortName: 'Engineering Workshops',
    cardSummary:
      'Machinery guarding, welding and cutting safety, electrical safety, chemical handling, housekeeping, and PPE control.',
    seoTitle: 'Engineering Workshop Safety Solutions | SAFE CUBE',
    metaDescription:
      'SAFE CUBE helps engineering workshops improve machinery guarding, welding safety, electrical safety, chemical handling, housekeeping, and PPE control.',
    heroHeading: 'Workplace Safety for Engineering Workshops',
    introduction:
      'SAFE CUBE helps engineering workshops address machinery guarding, welding and cutting safety, electrical safety, chemical handling, housekeeping, and PPE control. We understand that workshop environments involve specialised equipment, hot work, and skilled manual processes.',
    commonRisks: [
      'Machinery guarding and entanglement hazards',
      'Welding, cutting, and hot work safety',
      'Electrical safety and equipment condition',
      'Chemical handling and storage',
      'Housekeeping and clutter',
      'PPE availability and correct use',
    ],
    safeCubeSupport: [
      'Machinery guarding assessments',
      'Hot work safety reviews',
      'Electrical safety evaluations',
      'Chemical management guidance',
      'Housekeeping and PPE assessments',
      'Workshop staff training',
    ],
    ctaLabel: 'GET FREE CUBE SCORE',
    ctaHref: '/cube-score',
    featured: false,
    iconName: 'industries',
  },
  {
    slug: 'power-utilities',
    name: 'Power & Utilities',
    shortName: 'Power & Utilities',
    cardSummary:
      'Electrical safety, working at height, confined space entry, hazard identification, emergency response, and regulatory compliance.',
    seoTitle: 'Power & Utilities Safety Solutions | SAFE CUBE',
    metaDescription:
      'SAFE CUBE helps power and utilities businesses improve electrical safety, confined space entry, hazard identification, emergency response, and regulatory compliance.',
    heroHeading: 'Workplace Safety for Power & Utilities',
    introduction:
      'SAFE CUBE helps power and utilities businesses address electrical safety, working at height, confined space entry, hazard identification, emergency response, and regulatory compliance. We understand that utilities environments involve high-energy systems, remote work, and significant public safety responsibilities.',
    commonRisks: [
      'Electrical safety and arc flash hazards',
      'Working at height on towers and structures',
      'Confined space entry and atmospheric risks',
      'Hazard identification and risk assessment gaps',
      'Emergency response readiness',
      'Regulatory compliance and documentation',
    ],
    safeCubeSupport: [
      'Electrical safety assessments',
      'Confined space entry reviews',
      'Emergency response evaluations',
      'Hazard identification support',
      'Compliance documentation',
      'Operations and maintenance training',
    ],
    ctaLabel: 'GET FREE CUBE SCORE',
    ctaHref: '/cube-score',
    featured: false,
    iconName: 'industries',
  },
  {
    slug: 'corporate-offices',
    name: 'Corporate Offices',
    shortName: 'Corporate Offices',
    cardSummary:
      'Ergonomics, fire readiness, employee wellbeing, electrical safety, emergency planning, and basic compliance systems.',
    seoTitle: 'Corporate Office Safety Solutions | SAFE CUBE',
    metaDescription:
      'SAFE CUBE helps corporate offices improve ergonomics, fire readiness, employee wellbeing, electrical safety, emergency planning, and compliance.',
    heroHeading: 'Workplace Safety for Corporate Offices',
    introduction:
      'SAFE CUBE helps corporate offices address ergonomics, fire readiness, employee wellbeing, electrical safety, emergency planning, and basic compliance systems. We understand that office environments may appear low-risk but still require structured safety management and emergency preparedness.',
    commonRisks: [
      'Ergonomic and workstation issues',
      'Fire readiness gaps',
      'Electrical safety concerns',
      'Emergency planning weaknesses',
      'Indoor air quality and comfort',
      'Basic compliance documentation',
    ],
    safeCubeSupport: [
      'Ergonomic assessments',
      'Fire readiness evaluations',
      'Emergency planning support',
      'Electrical safety reviews',
      'Compliance documentation guidance',
      'Employee awareness training',
    ],
    ctaLabel: 'GET FREE CUBE SCORE',
    ctaHref: '/cube-score',
    featured: true,
    iconName: 'industries',
  },
  {
    slug: 'education',
    name: 'Educational Institutions',
    shortName: 'Education',
    cardSummary:
      'Campus safety, fire readiness, emergency preparedness, laboratory safety, student wellbeing, and compliance documentation.',
    seoTitle: 'Educational Institution Safety Solutions | SAFE CUBE',
    metaDescription:
      'SAFE CUBE helps educational institutions improve campus safety, fire readiness, emergency preparedness, laboratory safety, student wellbeing, and compliance.',
    heroHeading: 'Workplace Safety for Educational Institutions',
    introduction:
      'SAFE CUBE helps schools, colleges, and universities address campus safety, fire readiness, emergency preparedness, laboratory safety, student wellbeing, and compliance documentation. We understand that educational institutions have a duty of care to students, staff, and visitors.',
    commonRisks: [
      'Campus safety and security',
      'Fire readiness and evacuation planning',
      'Emergency preparedness for large groups',
      'Laboratory and workshop safety',
      'Student wellbeing and supervision',
      'Compliance documentation and records',
    ],
    safeCubeSupport: [
      'Campus safety assessments',
      'Fire readiness evaluations',
      'Emergency preparedness support',
      'Laboratory safety reviews',
      'Compliance documentation guidance',
      'Staff and faculty awareness training',
    ],
    ctaLabel: 'GET FREE CUBE SCORE',
    ctaHref: '/cube-score',
    featured: false,
    iconName: 'industries',
  },
  {
    slug: 'hospitality',
    name: 'Hospitality',
    shortName: 'Hospitality',
    cardSummary:
      'Guest safety, fire readiness, food safety, pool and recreation safety, employee wellbeing, and emergency planning.',
    seoTitle: 'Hospitality Safety Solutions | SAFE CUBE',
    metaDescription:
      'SAFE CUBE helps hospitality businesses improve guest safety, fire readiness, food safety, pool and recreation safety, employee wellbeing, and emergency planning.',
    heroHeading: 'Workplace Safety for Hospitality',
    introduction:
      'SAFE CUBE helps hotels, resorts, and hospitality businesses address guest safety, fire readiness, food safety, pool and recreation safety, employee wellbeing, and emergency planning. We understand that hospitality environments combine multiple operational areas with high guest expectations.',
    commonRisks: [
      'Guest safety and incident prevention',
      'Fire readiness and evacuation planning',
      'Food safety and kitchen hygiene',
      'Pool, gym, and recreation safety',
      'Employee wellbeing and fatigue',
      'Emergency planning for guests and staff',
    ],
    safeCubeSupport: [
      'Guest safety assessments',
      'Fire readiness evaluations',
      'Food safety reviews',
      'Recreation area safety checks',
      'Compliance documentation support',
      'Staff training and toolbox talks',
    ],
    ctaLabel: 'GET FREE CUBE SCORE',
    ctaHref: '/cube-score',
    featured: false,
    iconName: 'industries',
  },
  {
    slug: 'automotive-workshops',
    name: 'Automotive Workshops',
    shortName: 'Automotive Workshops',
    cardSummary:
      'Vehicle lifting, chemical handling, fire safety, PPE control, electrical equipment safety, and housekeeping.',
    seoTitle: 'Automotive Workshop Safety Solutions | SAFE CUBE',
    metaDescription:
      'SAFE CUBE helps automotive workshops improve vehicle lifting safety, chemical handling, fire safety, PPE control, electrical equipment safety, and housekeeping.',
    heroHeading: 'Workplace Safety for Automotive Workshops',
    introduction:
      'SAFE CUBE helps automotive workshops address vehicle lifting, chemical handling, fire safety, PPE control, electrical equipment safety, and housekeeping. We understand that workshop environments combine heavy equipment, chemicals, and skilled manual work.',
    commonRisks: [
      'Vehicle lifting and jack safety',
      'Chemical handling and storage',
      'Fire safety and flammable materials',
      'PPE availability and correct use',
      'Electrical equipment and tool condition',
      'Housekeeping and workshop organization',
    ],
    safeCubeSupport: [
      'Vehicle lifting safety assessments',
      'Chemical management reviews',
      'Fire safety evaluations',
      'PPE and housekeeping assessments',
      'Compliance documentation support',
      'Workshop staff training',
    ],
    ctaLabel: 'GET FREE CUBE SCORE',
    ctaHref: '/cube-score',
    featured: false,
    iconName: 'industries',
  },
  {
    slug: 'logistics-transport',
    name: 'Logistics & Transport',
    shortName: 'Logistics & Transport',
    cardSummary:
      'Vehicle safety, loading and unloading, driver fatigue, material handling, traffic management, and compliance documentation.',
    seoTitle: 'Logistics & Transport Safety Solutions | SAFE CUBE',
    metaDescription:
      'SAFE CUBE helps logistics and transport businesses improve vehicle safety, loading and unloading, driver fatigue management, traffic management, and compliance.',
    heroHeading: 'Workplace Safety for Logistics & Transport',
    introduction:
      'SAFE CUBE helps logistics and transport businesses address vehicle safety, loading and unloading, driver fatigue, material handling, traffic management, and compliance documentation. We understand that logistics environments combine vehicle operations, warehouse activities, and regulatory requirements.',
    commonRisks: [
      'Vehicle safety and maintenance',
      'Loading and unloading operations',
      'Driver fatigue and hours management',
      'Material handling and storage',
      'Traffic management and routing',
      'Compliance documentation and records',
    ],
    safeCubeSupport: [
      'Vehicle safety assessments',
      'Loading and unloading reviews',
      'Driver fatigue management guidance',
      'Traffic management evaluations',
      'Compliance documentation support',
      'Driver and warehouse staff training',
    ],
    ctaLabel: 'GET FREE CUBE SCORE',
    ctaHref: '/cube-score',
    featured: false,
    iconName: 'industries',
  },
];
